# Generated by Django 2.1.15 on 2020-12-05 12:37

from django.db import migrations, models
import django.utils.timezone
import user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userid', models.CharField(db_column='UserID', default=user_management.models.increment_role_id, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(db_column='Role', default='Intern', max_length=50)),
                ('dateofjoining', models.DateTimeField(blank=True, db_column='JoiningDate', default=django.utils.timezone.now)),
                ('mentor', models.CharField(blank=True, db_column='Mentor', max_length=50)),
                ('currentproject', models.CharField(blank=True, db_column='CurrentProject', max_length=50)),
                ('projectmentor', models.CharField(blank=True, db_column='ProjectMentor', max_length=50)),
                ('password', models.CharField(db_column='Password', default='user', max_length=50)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=50, null=True)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('contactno', models.CharField(blank=True, db_column='ContactNo', max_length=20, null=True)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=100, unique=True)),
                ('organizationemailaddress', models.CharField(blank=True, db_column='OrganizationEmailAddress', max_length=100, unique=True)),
                ('createddate', models.DateTimeField(db_column='CreatedDate', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'UserDetails',
                'managed': True,
            },
        ),
    ]
