# Generated by Django 2.1.15 on 2020-12-08 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.CharField(db_column='RoleID', max_length=50)),
                ('rolename', models.CharField(db_column='RoleName', max_length=50)),
                ('createddate', models.DateTimeField(db_column='CreatedOn', default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='userstatus',
            field=models.CharField(db_column='UserStatus', default='Enable', max_length=50),
        ),
    ]
