# Generated by Django 2.1.15 on 2020-12-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20201208_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='userroles',
            table='UserRoles',
        ),
    ]
