# Generated by Django 2.1.15 on 2020-12-08 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20201208_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='contactno',
            field=models.CharField(db_column='ContactNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='currentproject',
            field=models.CharField(db_column='CurrentProject', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='dateofjoining',
            field=models.DateTimeField(db_column='JoiningDate', default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mentor',
            field=models.CharField(db_column='Mentor', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='middlename',
            field=models.CharField(db_column='MiddleName', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='organizationemailaddress',
            field=models.CharField(db_column='OrganizationEmailAddress', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='projectmentor',
            field=models.CharField(db_column='ProjectMentor', max_length=50, null=True),
        ),
    ]
