# Generated by Django 2.1.15 on 2020-12-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20201208_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='organizationemailaddress',
            field=models.CharField(db_column='OrganizationEmailAddress', max_length=100, null=True),
        ),
    ]
