# Generated by Django 2.1.15 on 2020-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationlogs',
            name='contactno',
            field=models.CharField(db_column='ContactNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userauthenticationlogs',
            name='organizationemailaddress',
            field=models.CharField(db_column='OrganizationEmailAddress', max_length=100, null=True, unique=True),
        ),
    ]
