# Generated by Django 2.1.15 on 2020-12-08 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendanceLogs',
            fields=[
                ('logid', models.UUIDField(db_column='LogID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='UserID', max_length=20, null=True)),
                ('checkin', models.DateTimeField(db_column='CheckIn', default=datetime.datetime(2020, 12, 8, 13, 12, 13, 305479, tzinfo=utc))),
                ('checkout', models.DateTimeField(db_column='CheckOut', null=True)),
                ('approvalstatus', models.CharField(db_column='ApprovalStatus', default='Pending', max_length=50)),
                ('approvalstatusdate', models.DateField(db_column='ApprovalStatusDate', default=datetime.datetime(2020, 12, 8, 13, 12, 13, 305479, tzinfo=utc))),
                ('createdon', models.DateField(db_column='CreatedOn', default=datetime.datetime(2020, 12, 8, 13, 12, 13, 305479, tzinfo=utc))),
            ],
            options={
                'db_table': 'UserAttendanceLogs',
                'managed': True,
            },
        ),
    ]
