# Generated by Django 2.1.15 on 2020-12-13 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201210_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendancelogs',
            name='approvalstatusdate',
            field=models.DateField(db_column='ApprovalStatusDate', default=datetime.datetime(2020, 12, 13, 20, 10, 52, 889053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattendancelogs',
            name='checkin',
            field=models.DateTimeField(db_column='CheckIn', default=datetime.datetime(2020, 12, 13, 20, 10, 52, 889053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userattendancelogs',
            name='createdon',
            field=models.DateField(db_column='CreatedOn', default=datetime.datetime(2020, 12, 13, 20, 10, 52, 889053, tzinfo=utc)),
        ),
    ]
